services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sam
      POSTGRES_PASSWORD: sami8490
      POSTGRES_DB: movies_docker_test_db
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/scripts:/scripts

  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://sam:sami8490@db:5432/movies_docker_test_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: